version: "3.2"
services:
  flask:
    build: .
    restart: always
    environment:
      - APP_NAME=flaskApp
      - PYTHONPATH=/home/myuser
      - FLASK_ENV=production
    ports:
      - 80:5000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/home/myuser
